name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpcap-dev build-essential net-tools valgrind

    - name: Compile project
      run: make

    - name: Run dns with Valgrind 
      run: valgrind -s --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=1 ./analyseur -o data/dns.pcap -v 3

    - name: Run smtp with Valgrind 
      run: valgrind -s --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=1 ./analyseur -o data/smtp.pcap -v 3

    - name: Run dhcp with Valgrind 
      run: valgrind -s --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=1 ./analyseur -o data/dhcp.pcap -v 3
      
    - name: Run tests
      run : make dns

    - name: Clean build
      run: make clean