name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpcap-dev build-essential net-tools valgrind

    - name: Compile project
      run: make

    - name: Run tests with Valgrind
      run: |
        valgrind --leak-check=full --track-origins=yes --error-exitcode=1 make smtp
    
    - name: Run tests
      run : make dns

    - name: Clean build
      run: make clean